name: housingpricepred
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python>=3.8
  - scikit-learn>=0.23.1
  - pip
  - pip:
    - kedro>=0.16.4
    - mlflow>=1.0
    - psycopg2-binary